### ISSUE TITLE
[build] 빌드 에러가 납니다.

### ISSUE THREAD

**Issue by antholdings** [ANT-Holdings/lifeon#3]
node -v
v12.1.0
gulp -v
CLI version 2.1.0
Local version 4.0.2

$ gulp build
[14:08:58] Using gulpfile ~/WebstormProjects/lifeon/gulpfile.js
[14:08:58] Starting ‘build’...
[14:08:58] ‘build’ errored after 4 ms
[14:08:58] TypeError: gulp.hasTask is not a function
   at /Users/anth/WebstormProjects/lifeon/node_modules/run-sequence/index.js:23:22
   at Array.forEach (<anonymous>)
   at verifyTaskSets (/Users/anth/WebstormProjects/lifeon/node_modules/run-sequence/index.js:17:11)
   at runSequence (/Users/anth/WebstormProjects/lifeon/node_modules/run-sequence/index.js:130:2)
   at /Users/anth/WebstormProjects/lifeon/gulpfile.js:297:5
   at taskWrapper (/Users/anth/WebstormProjects/lifeon/node_modules/undertaker/lib/set-task.js:13:15)
   at bound (domain.js:415:14)
   at runBound (domain.js:428:12)
   at asyncRunner (/Users/anth/WebstormProjects/lifeon/node_modules/async-done/index.js:55:18)
   at processTicksAndRejections (internal/process/task_queues.js:82:9)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
yarnpkg.com
Yarn
Fast, reliable, and secure dependency management.

**Comment by koo6357** [comment]
gulp build 는 gh-pages 에 테스트 배포용으로 만들어 놨던 명령어 입니다.
gulp local 이라고 실행시켜주시면 localhost:5000/lifeon 에서 빌드결과 확인가능하시고,
빌드된 source는 lifeon 폴더에서 확인 가능합니다.
네이밍을 deploy이로 변경해놓지 않아 혼란을 드린것같아 죄송합니다.

**Comment by antholdings** [comment]
gulp 버젼을 낮춰보고 명령어를 수정해보아도 에러가 나네요...

gulp local
fs.js:27
const { Math, Object, Reflect } = primordials;
                                  ^

ReferenceError: primordials is not defined
    at fs.js:27:35
    at req_ (/Users/anth/WebstormProjects/lifeon/node_modules/natives/index.js:143:24)
    at Object.req [as require] (/Users/anth/WebstormProjects/lifeon/node_modules/natives/index.js:55:10)
    at Object.<anonymous> (/Users/anth/WebstormProjects/lifeon/node_modules/vinyl-fs/node_modules/graceful-fs/fs.js:1:37)
    at Module._compile (internal/modules/cjs/loader.js:759:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:770:10)
    at Module.load (internal/modules/cjs/loader.js:628:32)
    at Function.Module._load (internal/modules/cjs/loader.js:555:12)
    at Module.require (internal/modules/cjs/loader.js:666:19)
    at require (internal/modules/cjs/helpers.js:16:16)

**Comment by antholdings** [comment]
> gulp build 는 gh-pages 에 테스트 배포용으로 만들어 놨던 명령어 입니다.
> gulp local 이라고 실행시켜주시면 localhost:5000/lifeon 에서 빌드결과 확인가능하시고,
> 빌드된 source는 lifeon 폴더에서 확인 가능합니다.
> 네이밍을 deploy이로 변경해놓지 않아 혼란을 드린것같아 죄송합니다.

gulp 버젼을 낮춰보고 명령어를 수정해보아도 에러가 나네요...

gulp local
fs.js:27
const { Math, Object, Reflect } = primordials;
^

ReferenceError: primordials is not defined
at fs.js:27:35
at req_ (/Users/anth/WebstormProjects/lifeon/node_modules/natives/index.js:143:24)
at Object.req [as require] (/Users/anth/WebstormProjects/lifeon/node_modules/natives/index.js:55:10)
at Object. (/Users/anth/WebstormProjects/lifeon/node_modules/vinyl-fs/node_modules/graceful-fs/fs.js:1:37)
at Module._compile (internal/modules/cjs/loader.js:759:30)
at Object.Module._extensions..js (internal/modules/cjs/loader.js:770:10)
at Module.load (internal/modules/cjs/loader.js:628:32)
at Function.Module._load (internal/modules/cjs/loader.js:555:12)
at Module.require (internal/modules/cjs/loader.js:666:19)
at require (internal/modules/cjs/helpers.js:16:16)

**Comment by koo6357** [comment]
package.json 에 있는데로 3.9.1 버전 사용바랍니다.
얼마전에 릴리즈된 4점대 버전은 문법이 바뀌어서 에러가 날수 있습니다.

**Comment by antholdings** [comment]
> package.json 에 있는데로 3.9.1 버전 사용바랍니다.
> 얼마전에 릴리즈된 4점대 버전은 문법이 바뀌어서 에러가 날수 있습니다.
> 현재 소스 clone 하여 돌려보니 잘됩니다.

 ✘ anth@anthui-MBP  ~/WebstormProjects/lifeon   master  node -v
v12.1.0
 anth@anthui-MBP  ~/WebstormProjects/lifeon   master  gulp -v
CLI version 2.1.0
Local version 3.9.1
 anth@anthui-MBP  ~/WebstormProjects/lifeon   master  gulp local
fs.js:27
const { Math, Object, Reflect } = primordials;
                                  ^

ReferenceError: primordials is not defined
    at fs.js:27:35
    at req_ (/Users/anth/WebstormProjects/lifeon/node_modules/natives/index.js:143:24)
    at Object.req [as require] (/Users/anth/WebstormProjects/lifeon/node_modules/natives/index.js:55:10)
    at Object.<anonymous> (/Users/anth/WebstormProjects/lifeon/node_modules/vinyl-fs/node_modules/graceful-fs/fs.js:1:37)
    at Module._compile (internal/modules/cjs/loader.js:759:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:770:10)
    at Module.load (internal/modules/cjs/loader.js:628:32)
    at Function.Module._load (internal/modules/cjs/loader.js:555:12)
    at Module.require (internal/modules/cjs/loader.js:666:19)
    at require (internal/modules/cjs/helpers.js:16:16)
 ✘ anth@anthui-MBP  ~/WebstormProjects/lifeon   master  A

해당 에러가 계속나서 빌드된 부분도 커밋해서 올려주시면 감사하겠습니다.

**Comment by koo6357** [comment]
넵

**Comment by koo6357** [comment]
빌드파일과 회원가입 페이지를 추가하여 함께 업로드 되었습니다.
혹시나 나중에 소스를 수정시에 대비하여 말씀드리면,
CLI version 2.1.0
Local version 3.9.1
프로젝트 폴더의 gulp는 3.9.1로 보이나 글로벌로 설치된 gulp가 2.1.0 으로 오래전 버전이라 그런것같습니다.
루트의 node_modules 폴더에서 gulp 버전업이나  삭제후 3.9.1로 다시 설치하시면 빌드 될듯합니다.
